export type PrinterTipe = 'FDM' | 'Resin' | 'SLA' | 'SLS'
export type PrinterStatus = 'Idle' | 'Printing' | 'Maintenance' | 'Rusak'

export interface Printer {
  id: string
  nama: string
  model?: string
  tipe?: PrinterTipe
  watt: number
  status: PrinterStatus
  currentPesananId?: string
  totalJam: number
  catatan?: string
  createdAt: string
}

export interface Material {
  id: string
  nama: string
  tipe?: string
  warna?: string
  stok: number
  hargaBeliPerGram: number
  hargaJualPerGram: number
  marginPerGram: number
  stokMinimum?: number
  createdAt: string
}

export type PesananStatus = 'Antrian' | 'Printing' | 'Selesai' | 'Dibatalkan'

export interface ColorEntry {
  materialId: string
  materialNama: string
  beratGram: number
}

export interface Pesanan {
  id: string
  nama: string
  klien: string
  tipe?: string
  printerId: string
  materialId: string
  beratMaterial: number
  estimasiJam: number
  markup: number
  hpp: number
  hargaRekomendasi: number
  nilaiJual: number
  diskonTipe?: 'persen' | 'rupiah'
  diskonNilai: number
  hargaFinal: number
  hargaBeliPerGramSnapshot: number
  hargaJualPerGramSnapshot: number
  wattSnapshot: number
  tarifListrikSnapshot: number
  status: PesananStatus
  deadline?: string
  catatan?: string
  createdAt: string
  printingAt?: string
  completedAt?: string
  cancelledAt?: string
  printerNama?: string
  materialNama?: string
  multiColorData?: ColorEntry[]
}

export type TransaksiJenis = 'pendapatan' | 'pengeluaran'

export interface Transaksi {
  id: string
  jenis: TransaksiJenis
  nama: string
  kategori?: string
  jumlah: number
  hppSnapshot?: number
  tanggal: string
  pesananId?: string
  sourceType?: 'pesanan' | 'manual'
  sourceId?: string
  isAutoGenerated: boolean
  createdAt: string
}

export interface Aktivitas {
  id: string
  modul: 'Pesanan' | 'Printer' | 'Material' | 'Keuangan' | 'Sistem'
  aksi: string
  refId?: string
  deskripsi: string
  createdAt: string
}

export interface Klien {
  id: string
  nama: string
  telepon?: string
  email?: string
  alamat?: string
  catatan?: string
  createdAt: string
  totalPesanan: number
  totalNilai: number
}

export interface Setting {
  tarifListrik: number
  markupDefault: number
  namaToko: string
  alamat: string
  telepon: string
  logoBase64?: string
  bankNama?: string
  bankNoRekening?: string
  bankAtasNama?: string
}

export interface PricingPreview {
  biayaMaterial: number
  marginMaterial: number
  biayaListrik: number
  hpp: number
  hargaRekomendasi: number
  profitEstimasi: number
}

export interface DashboardKPI {
  totalOrderAktif: number
  totalOrderAntrian: number
  totalOrderPrinting: number
  totalOrderSelesaiBulanIni: number
  totalOrderDibatalkanBulanIni: number
  totalPrinterIdle: number
  totalPrinterPrinting: number
  totalMaterialHampirHabis: number
  totalPendapatanBulanIni: number
  totalPengeluaranBulanIni: number
  profitBulanIni: number
  rataRataNilaiJual: number
  rataRataHpp: number
  rataRataEstimasiJam: number
  orderMendekatiDeadline: Pesanan[]
  materialHampirHabis: Material[]
  aktivitasTerbaru: Aktivitas[]
  trendPendapatanPct: number | null
  trendPengeluaranPct: number | null
  trendProfitPct: number | null
  trendOrderSelesaiPct: number | null
}
