import { Transaksi, Setting } from '../types'

export function generateLaporanHTML(bulan: string, transaksis: Transaksi[], setting: Setting): string {
  const fmt = (n: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(n)
  const fmtTgl = (s: string) => new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(s))
  const [yr, mo] = bulan.split('-').map(Number)
  const period = new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(new Date(yr, mo - 1, 1))
  const totalPenjualan = transaksis.filter(t => t.jenis === 'pendapatan' && t.isAutoGenerated).reduce((a, t) => a + t.jumlah, 0)
  const pendapatan = transaksis.filter(t => t.jenis === 'pendapatan').reduce((a, t) => a + (t.isAutoGenerated ? t.jumlah - (t.hppSnapshot ?? 0) : t.jumlah), 0)
  const pengeluaran = transaksis.filter(t => t.jenis === 'pengeluaran').reduce((a, t) => a + t.jumlah, 0)
  const profit = pendapatan - pengeluaran
  const rows = transaksis.map(t => `
    <tr>
      <td>${fmtTgl(t.tanggal)}</td>
      <td>${t.nama}${t.isAutoGenerated ? ' <span class="badge">Auto</span>' : ''}</td>
      <td>${t.kategori ?? '—'}</td>
      <td class="${t.jenis === 'pendapatan' ? 'inc' : 'exp'}">${t.jenis === 'pendapatan' ? 'Pendapatan' : 'Pengeluaran'}</td>
      <td style="text-align:right;" class="${t.jenis === 'pendapatan' ? 'inc' : 'exp'}">${t.jenis === 'pendapatan' ? '+' : '−'}${fmt(t.jumlah)}</td>
    </tr>`).join('')
  return `<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><title>Laporan Keuangan ${period}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:Arial,sans-serif;font-size:12px;color:#111;padding:32px 40px;background:#fff}
  h1{font-size:20px;font-weight:700;margin-bottom:4px}
  .sub{font-size:12px;color:#666;margin-bottom:24px}
  .summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:28px}
  .card{border:1px solid #e0e0e0;border-radius:8px;padding:14px 16px}
  .card-label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#888;margin-bottom:6px}
  .card-value{font-size:18px;font-weight:700}
  .inc{color:#16a34a}.exp{color:#dc2626}.acc{color:#2563eb}
  table{width:100%;border-collapse:collapse}
  th{background:#f5f5f5;text-align:left;padding:9px 10px;font-size:11px;border-bottom:2px solid #ddd;font-weight:700}
  td{padding:8px 10px;border-bottom:1px solid #f0f0f0;font-size:12px;vertical-align:middle}
  tr:last-child td{border-bottom:none}
  .badge{display:inline-block;font-size:9px;font-weight:700;background:#eff6ff;color:#2563eb;border-radius:4px;padding:1px 5px;margin-left:4px;vertical-align:middle}
  .footer{margin-top:28px;font-size:10px;color:#aaa;text-align:right;border-top:1px solid #eee;padding-top:10px}
  @media print{body{padding:20px 28px}}
</style></head><body>
<h1>${setting.namaToko ?? 'Laporan Keuangan'}</h1>
<div class="sub">Laporan Keuangan · ${period}${setting.alamat ? ' · ' + setting.alamat : ''}</div>
<div class="summary">
  <div class="card"><div class="card-label">Total Penjualan Kotor</div><div class="card-value" style="color:#0d9488">${fmt(totalPenjualan)}</div></div>
  <div class="card"><div class="card-label">Pendapatan</div><div class="card-value inc">${fmt(pendapatan)}</div></div>
  <div class="card"><div class="card-label">Pengeluaran</div><div class="card-value exp">${fmt(pengeluaran)}</div></div>
  <div class="card"><div class="card-label">Profit</div><div class="card-value ${profit >= 0 ? 'inc' : 'exp'}">${fmt(profit)}</div></div>
</div>
<table>
  <thead><tr><th>Tanggal</th><th>Keterangan</th><th>Kategori</th><th>Jenis</th><th style="text-align:right">Jumlah</th></tr></thead>
  <tbody>${rows || '<tr><td colspan="5" style="text-align:center;color:#aaa;padding:20px">Tidak ada transaksi bulan ini</td></tr>'}</tbody>
</table>
<div class="footer">Dicetak ${new Intl.DateTimeFormat('id-ID', { dateStyle: 'full' }).format(new Date())} · ${setting.namaToko ?? ''}</div>
</body></html>`
}
