import { transaksiRepository } from '../repositories/transaksi.repository'
import { aktivitasRepository } from '../repositories/aktivitas.repository'
import { HttpError } from '../utils'

export const transaksiService = {
  getAll() { return transaksiRepository.findAll() },
  getByBulan(bulan: string) { return transaksiRepository.findByBulan(bulan) },
  createManual(payload: any) {
    if (!payload.nama?.trim()) throw new HttpError(400, 'Nama transaksi wajib diisi')
    if (payload.jumlah <= 0) throw new HttpError(400, 'Jumlah harus lebih dari 0')
    if (!payload.tanggal) throw new HttpError(400, 'Tanggal wajib diisi')
    const transaksi = transaksiRepository.createManual(payload)
    aktivitasRepository.catat('Keuangan', 'TAMBAH', `Transaksi manual "${transaksi!.nama}" (${transaksi!.jenis}) Rp ${transaksi!.jumlah.toLocaleString('id-ID')} dicatat`, transaksi!.id)
    return transaksi
  },
  delete(id: string) {
    const existing = transaksiRepository.findById(id)
    if (!existing) throw new HttpError(404, 'Transaksi tidak ditemukan')
    if (existing.isAutoGenerated) throw new HttpError(400, 'Transaksi otomatis dari pesanan tidak dapat dihapus')
    if (!transaksiRepository.delete(id)) throw new HttpError(400, 'Gagal menghapus transaksi')
    aktivitasRepository.catat('Keuangan', 'HAPUS', `Transaksi manual "${existing.nama}" dihapus`, id)
  }
}
