import { Router } from 'express'
import { transaksiService } from '../services/transaksi.service'
import { transaksiRepository } from '../repositories/transaksi.repository'
import { asyncHandler } from '../middleware/error.middleware'
import { toCsv } from '../utils'

export const transaksiRouter = Router()

transaksiRouter.get('/export/csv', asyncHandler(async (_req, res) => {
  const data = transaksiRepository.findAll()
  const headers = ['ID', 'Jenis', 'Nama', 'Kategori', 'Jumlah(Rp)', 'Tanggal', 'Auto']
  const rows = data.map(t => [
    t.id, t.jenis, t.nama, t.kategori ?? '', String(t.jumlah), t.tanggal, t.isAutoGenerated ? 'Ya' : 'Tidak'
  ])
  const csv = toCsv([headers, ...rows])
  res.setHeader('Content-Type', 'text/csv; charset=utf-8')
  res.setHeader('Content-Disposition', `attachment; filename="transaksi-${new Date().toISOString().slice(0, 10)}.csv"`)
  res.send('﻿' + csv)
}))
transaksiRouter.get('/bulan/:bulan', asyncHandler(async (req) => transaksiService.getByBulan(String(req.params.bulan))))
transaksiRouter.get('/', asyncHandler(async () => transaksiService.getAll()))
transaksiRouter.post('/', asyncHandler(async (req) => transaksiService.createManual(req.body)))
transaksiRouter.delete('/:id', asyncHandler(async (req) => { transaksiService.delete(String(req.params.id)); return null }))
