import { app, BrowserWindow, shell, ipcMain, dialog } from 'electron'
import { join } from 'path'
import { tmpdir } from 'os'
import { randomBytes } from 'crypto'
import { electronApp, optimizer, is } from '@electron-toolkit/utils'
import { initDb, closeDb, getDb, getDbPath } from './db'
import { registerAllHandlers } from './ipc'
import { pesananRepository } from './repositories/pesanan.repository'
import { transaksiRepository } from './repositories/transaksi.repository'
import { generateInvoiceHTML } from './services/nota.service'
import { settingRepository } from './repositories/setting.repository'
import * as fs from 'fs'

function generateLaporanHTML(bulan: string, transaksis: any[], setting: any): string {
  const fmt = (n: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(n)
  const fmtTgl = (s: string) => new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(s))
  const [yr, mo] = bulan.split('-').map(Number)
  const period = new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(new Date(yr, mo - 1, 1))
  const totalPenjualan = transaksis.filter(t => t.jenis === 'pendapatan' && t.isAutoGenerated).reduce((a: number, t: any) => a + t.jumlah, 0)
  const pendapatan = transaksis.filter(t => t.jenis === 'pendapatan').reduce((a: number, t: any) => a + (t.isAutoGenerated ? t.jumlah - (t.hppSnapshot ?? 0) : t.jumlah), 0)
  const pengeluaran = transaksis.filter(t => t.jenis === 'pengeluaran').reduce((a: number, t: any) => a + t.jumlah, 0)
  const profit = pendapatan - pengeluaran
  const rows = transaksis.map(t => `
    <tr>
      <td>${fmtTgl(t.tanggal)}</td>
      <td>${t.nama}${t.isAutoGenerated ? ' <span class="badge">Auto</span>' : ''}</td>
      <td>${t.kategori ?? '—'}</td>
      <td class="${t.jenis === 'pendapatan' ? 'inc' : 'exp'}">${t.jenis === 'pendapatan' ? 'Pendapatan' : 'Pengeluaran'}</td>
      <td style="text-align:right;" class="${t.jenis === 'pendapatan' ? 'inc' : 'exp'}">${t.jenis === 'pendapatan' ? '+' : '−'}${fmt(t.jumlah)}</td>
    </tr>`).join('')
  return `<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><title>Laporan Keuangan ${period}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:Arial,sans-serif;font-size:12px;color:#111;padding:32px 40px;background:#fff}
  h1{font-size:20px;font-weight:700;margin-bottom:4px}
  .sub{font-size:12px;color:#666;margin-bottom:24px}
  .summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:28px}
  .card{border:1px solid #e0e0e0;border-radius:8px;padding:14px 16px}
  .card-label{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#888;margin-bottom:6px}
  .card-value{font-size:18px;font-weight:700}
  .inc{color:#16a34a}.exp{color:#dc2626}.acc{color:#2563eb}
  table{width:100%;border-collapse:collapse}
  th{background:#f5f5f5;text-align:left;padding:9px 10px;font-size:11px;border-bottom:2px solid #ddd;font-weight:700}
  td{padding:8px 10px;border-bottom:1px solid #f0f0f0;font-size:12px;vertical-align:middle}
  tr:last-child td{border-bottom:none}
  .badge{display:inline-block;font-size:9px;font-weight:700;background:#eff6ff;color:#2563eb;border-radius:4px;padding:1px 5px;margin-left:4px;vertical-align:middle}
  .footer{margin-top:28px;font-size:10px;color:#aaa;text-align:right;border-top:1px solid #eee;padding-top:10px}
  @media print{body{padding:20px 28px}}
</style></head><body>
<h1>${setting.namaToko ?? 'Laporan Keuangan'}</h1>
<div class="sub">Laporan Keuangan · ${period}${setting.alamat ? ' · ' + setting.alamat : ''}</div>
<div class="summary">
  <div class="card"><div class="card-label">Total Penjualan Kotor</div><div class="card-value" style="color:#0d9488">${fmt(totalPenjualan)}</div></div>
  <div class="card"><div class="card-label">Pendapatan</div><div class="card-value inc">${fmt(pendapatan)}</div></div>
  <div class="card"><div class="card-label">Pengeluaran</div><div class="card-value exp">${fmt(pengeluaran)}</div></div>
  <div class="card"><div class="card-label">Profit</div><div class="card-value ${profit >= 0 ? 'inc' : 'exp'}">${fmt(profit)}</div></div>
</div>
<table>
  <thead><tr><th>Tanggal</th><th>Keterangan</th><th>Kategori</th><th>Jenis</th><th style="text-align:right">Jumlah</th></tr></thead>
  <tbody>${rows || '<tr><td colspan="5" style="text-align:center;color:#aaa;padding:20px">Tidak ada transaksi bulan ini</td></tr>'}</tbody>
</table>
<div class="footer">Dicetak ${new Intl.DateTimeFormat('id-ID',{dateStyle:'full'}).format(new Date())} · ${setting.namaToko ?? ''}</div>
</body></html>`
}

function toCsv(rows: string[][]): string {
  return rows.map(row =>
    row.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')
  ).join('\r\n')
}

async function htmlToPDF(html: string): Promise<Buffer> {
  const tmpPath = join(tmpdir(), `kyndel-${randomBytes(6).toString('hex')}.html`)
  fs.writeFileSync(tmpPath, html, 'utf-8')
  const win = new BrowserWindow({ show: false, webPreferences: { javascript: false } })
  try {
    await win.loadFile(tmpPath)
    const buf = await win.webContents.printToPDF({
      pageSize: 'A4', printBackground: true, margins: { marginType: 'none' }
    })
    return buf
  } finally {
    win.close()
    try { fs.unlinkSync(tmpPath) } catch {}
  }
}


function createWindow(): void {
  const mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 900,
    minHeight: 600,
    show: false,
    autoHideMenuBar: true,
    title: 'KYndel 3D',
    icon: join(__dirname, '../../build/icon.png'),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false,
      contextIsolation: true
    }
  })

  mainWindow.on('ready-to-show', () => mainWindow.show())
  mainWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  ipcMain.handle('app:setTitle', (_event, title: string) => {
    mainWindow.setTitle(title)
  })

  ipcMain.handle('nota:getInvoiceHTML', async (_event, ids: string[], tagihanKepada?: string) => {
    try {
      const pesanans = ids.map(id => pesananRepository.findById(id)).filter((p): p is NonNullable<typeof p> => p !== null)
      if (pesanans.length === 0) return { success: false, error: 'Tidak ada pesanan ditemukan' }
      const sh = settingRepository.get()
      return { success: true, data: generateInvoiceHTML(pesanans, { nama: sh.namaToko, alamat: sh.alamat, telepon: sh.telepon, logoBase64: sh.logoBase64, bankNama: sh.bankNama, bankNoRekening: sh.bankNoRekening, bankAtasNama: sh.bankAtasNama }, tagihanKepada) }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      return { success: false, error: msg }
    }
  })

  ipcMain.handle('nota:exportInvoicePDF', async (_event, ids: string[], tagihanKepada?: string) => {
    try {
      const pesanans = ids.map(id => pesananRepository.findById(id)).filter((p): p is NonNullable<typeof p> => p !== null)
      if (pesanans.length === 0) return { success: false, error: 'Tidak ada pesanan ditemukan' }
      const kliens = [...new Set(pesanans.map(p => p.klien))]
      const defaultName = `Invoice-${kliens.join('-').replace(/\s+/g, '-')}-${new Date().toISOString().slice(0, 10)}.pdf`
      const { canceled, filePath } = await dialog.showSaveDialog(mainWindow, {
        title: 'Simpan Invoice PDF',
        defaultPath: defaultName,
        filters: [{ name: 'PDF', extensions: ['pdf'] }]
      })
      if (canceled || !filePath) return { success: true }
      const si = settingRepository.get()
      const buf = await htmlToPDF(generateInvoiceHTML(pesanans, { nama: si.namaToko, alamat: si.alamat, telepon: si.telepon, logoBase64: si.logoBase64, bankNama: si.bankNama, bankNoRekening: si.bankNoRekening, bankAtasNama: si.bankAtasNama }, tagihanKepada))
      fs.writeFileSync(filePath, buf)
      return { success: true }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      return { success: false, error: msg }
    }
  })

  ipcMain.handle('db:backup', async () => {
    try {
      const dbPath = getDbPath()
      getDb().pragma('wal_checkpoint(TRUNCATE)')
      const defaultName = `kyndel3d-backup-${new Date().toISOString().slice(0, 10)}.db`
      const { canceled, filePath } = await dialog.showSaveDialog(mainWindow, {
        title: 'Simpan Backup Database',
        defaultPath: defaultName,
        filters: [{ name: 'SQLite Database', extensions: ['db'] }]
      })
      if (canceled || !filePath) return { success: true, data: null }
      fs.copyFileSync(dbPath, filePath)
      return { success: true, data: filePath }
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) }
    }
  })

  ipcMain.handle('db:restore', async () => {
    try {
      const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
        title: 'Pilih File Backup Database',
        filters: [{ name: 'SQLite Database', extensions: ['db'] }],
        properties: ['openFile']
      })
      if (canceled || filePaths.length === 0) return { success: true, data: null }
      const filePath = filePaths[0]
      const buf = Buffer.alloc(16)
      const fd = fs.openSync(filePath, 'r')
      fs.readSync(fd, buf, 0, 16, 0)
      fs.closeSync(fd)
      if (!buf.slice(0, 15).toString('utf8').startsWith('SQLite format 3')) {
        return { success: false, error: 'File yang dipilih bukan database SQLite yang valid' }
      }
      const dbPath = getDbPath()
      closeDb()
      fs.copyFileSync(filePath, dbPath)
      initDb()
      return { success: true, data: filePath }
    } catch (err) {
      try { initDb() } catch {}
      return { success: false, error: err instanceof Error ? err.message : String(err) }
    }
  })

  ipcMain.handle('export:pesanan', async () => {
    try {
      const defaultName = `pesanan-${new Date().toISOString().slice(0, 10)}.csv`
      const { canceled, filePath } = await dialog.showSaveDialog(mainWindow, {
        title: 'Export Data Pesanan',
        defaultPath: defaultName,
        filters: [{ name: 'CSV', extensions: ['csv'] }]
      })
      if (canceled || !filePath) return { success: true }
      const data = pesananRepository.findAll()
      const headers = ['ID', 'Nama', 'Klien', 'Tipe', 'Printer', 'Material', 'Berat(g)', 'Est.Jam', 'Markup%', 'HPP', 'Harga Rekomendasi', 'Nilai Jual', 'Harga Final', 'Status', 'Deadline', 'Dibuat', 'Selesai']
      const rows = data.map(p => [
        p.id, p.nama, p.klien, p.tipe ?? '', p.printerNama ?? '', p.materialNama ?? '',
        String(Math.round(p.beratMaterial * 1000)), String(p.estimasiJam), String(p.markup),
        String(p.hpp), String(p.hargaRekomendasi), String(p.nilaiJual), String(p.hargaFinal),
        p.status, p.deadline ?? '', p.createdAt.slice(0, 10), p.completedAt?.slice(0, 10) ?? ''
      ])
      fs.writeFileSync(filePath, '﻿' + toCsv([headers, ...rows]), 'utf-8')
      return { success: true }
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) }
    }
  })

  ipcMain.handle('laporan:keuanganBulan', async (_event, bulan: string) => {
    try {
      const defaultName = `laporan-keuangan-${bulan}.pdf`
      const { canceled, filePath } = await dialog.showSaveDialog(mainWindow, {
        title: 'Simpan Laporan Keuangan',
        defaultPath: defaultName,
        filters: [{ name: 'PDF', extensions: ['pdf'] }]
      })
      if (canceled || !filePath) return { success: true }
      const si = settingRepository.get()
      const transaksis = transaksiRepository.findByBulan(bulan)
      const html = generateLaporanHTML(bulan, transaksis, si)
      const buf = await htmlToPDF(html)
      fs.writeFileSync(filePath, buf)
      return { success: true }
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) }
    }
  })

  ipcMain.handle('export:transaksi', async () => {
    try {
      const defaultName = `transaksi-${new Date().toISOString().slice(0, 10)}.csv`
      const { canceled, filePath } = await dialog.showSaveDialog(mainWindow, {
        title: 'Export Data Transaksi',
        defaultPath: defaultName,
        filters: [{ name: 'CSV', extensions: ['csv'] }]
      })
      if (canceled || !filePath) return { success: true }
      const data = transaksiRepository.findAll()
      const headers = ['ID', 'Jenis', 'Nama', 'Kategori', 'Jumlah(Rp)', 'Tanggal', 'Auto']
      const rows = data.map(t => [
        t.id, t.jenis, t.nama, t.kategori ?? '', String(t.jumlah), t.tanggal, t.isAutoGenerated ? 'Ya' : 'Tidak'
      ])
      fs.writeFileSync(filePath, '﻿' + toCsv([headers, ...rows]), 'utf-8')
      return { success: true }
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) }
    }
  })

  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

app.whenReady().then(() => {
  electronApp.setAppUserModelId('com.kyndel3d.app')
  app.on('browser-window-created', (_, window) => {
    optimizer.watchWindowShortcuts(window)
  })
  initDb()
  registerAllHandlers()
  createWindow()
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  closeDb()
  if (process.platform !== 'darwin') app.quit()
})
