import { useState, useEffect, useCallback, useMemo } from 'react'
import { useAppDispatch, useAppSelector } from '../store/hooks'
import { fetchTransaksi, fetchTransaksiByBulan, createTransaksiManual, deleteTransaksi } from '../store/transaksiSlice'
import { api, formatRp, formatTgl, downloadBlob } from '../lib/api'
import { pctChange } from '../lib/trend'
import { Transaksi } from '../types'
import ConfirmDialog from '../components/ui/ConfirmDialog'
import EmptyState from '../components/ui/EmptyState'
import FormField from '../components/ui/FormField'
import Modal from '../components/ui/Modal'
import KpiCard from '../components/ui/KpiCard'
import TrendChipInline from '../components/ui/TrendChip'
import { Table, TableHeader, TableBody, TableFooter, TableRow, TableHead, TableCell } from '../components/ui/Table'
import LineChart, { LineSeries } from '../components/charts/LineChart'

type ChartPeriod = 'minggu' | 'bulan' | 'tahun'

interface ChartPoint {
  label: string
  penjualan: number
  pengeluaran: number
  profit: number
}

const keuanganSeries: LineSeries<ChartPoint>[] = [
  { key: 'penjualan', label: 'Penjualan', color: 'var(--success)' },
  { key: 'pengeluaran', label: 'Pengeluaran', color: 'var(--danger)' },
  { key: 'profit', label: 'Profit', color: 'var(--accent)' },
]

function groupTransaksi(txs: Transaksi[]) {
  const penjualan   = txs.filter(t => t.jenis === 'pendapatan' && t.isAutoGenerated).reduce((a, t) => a + t.jumlah, 0)
  const pendapatan  = txs.filter(t => t.jenis === 'pendapatan').reduce((a, t) => a + (t.isAutoGenerated ? t.jumlah - (t.hppSnapshot ?? 0) : t.jumlah), 0)
  const pengeluaran = txs.filter(t => t.jenis === 'pengeluaran').reduce((a, t) => a + t.jumlah, 0)
  return { penjualan, pendapatan, pengeluaran, profit: pendapatan - pengeluaran }
}

function prevMonthStr(ym: string): string {
  const [y, m] = ym.split('-').map(Number)
  const d = new Date(y, m - 2, 1)
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}


export default function KeuanganPage() {
  const dispatch = useAppDispatch()
  const { items: allTransaksi, bulanItems: transaksis, status } = useAppSelector((s) => s.transaksi)
  const [chartLoading, setChartLoading] = useState(false)
  const [showForm, setShowForm] = useState(false)
  const [confirm, setConfirm] = useState<Transaksi | null>(null)
  const [error, setError] = useState('')
  const [bulan, setBulan] = useState(new Date().toISOString().slice(0, 7))
  const [chartPeriod, setChartPeriod] = useState<ChartPeriod>('bulan')
  const [form, setForm] = useState({ jenis: 'pengeluaran', nama: '', kategori: '', jumlah: '', tanggal: new Date().toISOString().split('T')[0] })

  const load = useCallback(() => { dispatch(fetchTransaksiByBulan(bulan)) }, [dispatch, bulan])
  const loadAll = useCallback(async () => {
    setChartLoading(true)
    await dispatch(fetchTransaksi())
    setChartLoading(false)
  }, [dispatch])

  useEffect(() => { load() }, [load])
  useEffect(() => { loadAll() }, [loadAll])

  const totalPenjualan = transaksis.filter(t => t.jenis === 'pendapatan' && t.isAutoGenerated).reduce((a, t) => a + t.jumlah, 0)
  const pendapatan     = transaksis.filter(t => t.jenis === 'pendapatan').reduce((a, t) => a + (t.isAutoGenerated ? t.jumlah - (t.hppSnapshot ?? 0) : t.jumlah), 0)
  const pengeluaran    = transaksis.filter(t => t.jenis === 'pengeluaran').reduce((a, t) => a + t.jumlah, 0)
  const profit = pendapatan - pengeluaran

  const chartData = useMemo<ChartPoint[]>(() => {
    if (chartPeriod === 'minggu') {
      return Array.from({ length: 7 }, (_, i) => {
        const d = new Date(); d.setDate(d.getDate() - 6 + i)
        const dateStr = d.toISOString().split('T')[0]
        return {
          label: new Intl.DateTimeFormat('id-ID', { weekday: 'short', day: 'numeric' }).format(d),
          ...groupTransaksi(allTransaksi.filter(t => t.tanggal.startsWith(dateStr)))
        }
      })
    }

    if (chartPeriod === 'bulan') {
      const [yr, mo] = bulan.split('-').map(Number)
      const days = new Date(yr, mo, 0).getDate()
      return Array.from({ length: days }, (_, i) => {
        const dateStr = `${bulan}-${String(i + 1).padStart(2, '0')}`
        return { label: `${i + 1}`, ...groupTransaksi(allTransaksi.filter(t => t.tanggal.startsWith(dateStr))) }
      })
    }

    // tahun
    const year = bulan.split('-')[0]
    const months = ['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des']
    return Array.from({ length: 12 }, (_, i) => {
      const mStr = `${year}-${String(i + 1).padStart(2, '0')}`
      return { label: months[i], ...groupTransaksi(allTransaksi.filter(t => t.tanggal.startsWith(mStr))) }
    })
  }, [chartPeriod, bulan, allTransaksi])

  // Bulan lalu (untuk chip tren pada kartu KPI)
  const prevBulan = useMemo(() => prevMonthStr(bulan), [bulan])
  const prev = useMemo(
    () => groupTransaksi(allTransaksi.filter(t => t.tanggal.startsWith(prevBulan))),
    [allTransaksi, prevBulan]
  )

  // High/Low/Change dari profit pada periode yang sedang ditampilkan di grafik
  const periodStats = useMemo(() => {
    const vals = chartData.map(d => d.profit)
    if (vals.length === 0) return null
    return { high: Math.max(...vals), low: Math.min(...vals), change: pctChange(vals[vals.length - 1], vals[0]) }
  }, [chartData])

  // Tandai "hari ini" di grafik dengan garis referensi putus-putus, kalau periode yang aktif memuatnya
  const todayLabel = useMemo(() => {
    const now = new Date()
    if (chartPeriod === 'minggu') return chartData[chartData.length - 1]?.label
    if (chartPeriod === 'bulan') return bulan === now.toISOString().slice(0, 7) ? String(now.getDate()) : undefined
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des']
    return bulan.split('-')[0] === String(now.getFullYear()) ? months[now.getMonth()] : undefined
  }, [chartPeriod, bulan, chartData])

  const handleSubmit = async () => {
    setError('')
    try {
      await dispatch(createTransaksiManual({ jenis: form.jenis, nama: form.nama, kategori: form.kategori || undefined, jumlah: +form.jumlah, tanggal: form.tanggal })).unwrap()
      setShowForm(false)
      setForm({ jenis: 'pengeluaran', nama: '', kategori: '', jumlah: '', tanggal: new Date().toISOString().split('T')[0] })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Gagal mencatat transaksi')
    }
  }

  const handleCetakLaporan = async () => {
    try {
      const html = await api.get<string>(`/laporan/keuangan/${bulan}/html`)
      const win = window.open('', '_blank')
      if (!win) return
      win.document.write(html)
      win.document.close()
      win.onload = () => win.print()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Gagal membuat laporan')
    }
  }

  const handleExportCsv = () => downloadBlob('/transaksi/export/csv', `transaksi-${new Date().toISOString().slice(0, 10)}.csv`).catch(err => setError(err.message))

  const periodLabel = chartPeriod === 'minggu' ? '7 Hari Terakhir'
    : chartPeriod === 'bulan' ? new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(new Date(bulan + '-01'))
    : `Tahun ${bulan.split('-')[0]}`

  if (status === 'loading' && transaksis.length === 0) return <div className="page-loading"><div className="spinner" /><span>Memuat keuangan...</span></div>

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--spacing-md)' }}>

      {/* Top bar */}
      <div className="animate-fade-up" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <label className="form-label" style={{ margin: 0 }}>Bulan:</label>
          <input type="month" value={bulan} onChange={e => setBulan(e.target.value)} style={{ width: 'auto' }} />
        </div>
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
          <button className="btn btn-secondary" onClick={handleCetakLaporan} title="Cetak laporan keuangan bulan ini sebagai PDF">
            <svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M4 7V3a1 1 0 011-1h6a1 1 0 011 1v4"/>
              <path d="M2 7h12a1 1 0 011 1v4a1 1 0 01-1 1H2a1 1 0 01-1-1V8a1 1 0 011-1z"/>
              <path d="M4.5 14v-2h7v2"/>
            </svg>
            Cetak Laporan
          </button>
          <button className="btn btn-secondary" onClick={handleExportCsv} title="Export semua transaksi ke CSV">
            <svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M8 2v8M5 7l3 3 3-3M3 13h10"/>
            </svg>
            CSV
          </button>
          <button className="btn btn-primary" onClick={() => setShowForm(true)}>
            <svg width="12" height="12" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
              <line x1="8" y1="2" x2="8" y2="14"/><line x1="2" y1="8" x2="14" y2="8"/>
            </svg>
            Catat Transaksi
          </button>
        </div>
      </div>

      {/* KPI cards: 4 columns, tren bulan ini vs bulan lalu */}
      <div className="animate-fade-up-1 rgrid-4" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 'var(--spacing-md)' }}>
        <KpiCard
          label="Total Penjualan Kotor" value={formatRp(totalPenjualan)} sub="Dari pesanan selesai"
          trend={pctChange(totalPenjualan, prev.penjualan)}
          color="var(--teal)" accent="var(--teal)" accentLight="var(--teal-light)"
        />
        <KpiCard
          label="Pendapatan" value={formatRp(pendapatan)}
          trend={pctChange(pendapatan, prev.pendapatan)}
          color="var(--success)" accent="var(--success)" accentLight="var(--success-light)"
        />
        <KpiCard
          label="Pengeluaran" value={formatRp(pengeluaran)}
          trend={pctChange(pengeluaran, prev.pengeluaran)} invertTrend
          color="var(--danger)" accent="var(--danger)" accentLight="var(--danger-light)"
        />
        <KpiCard
          label="Profit" value={formatRp(profit)}
          trend={pctChange(profit, prev.profit)}
          color={profit >= 0 ? 'var(--success)' : 'var(--danger)'}
          accent={profit >= 0 ? 'var(--success)' : 'var(--danger)'}
          accentLight={profit >= 0 ? 'var(--success-light)' : 'var(--danger-light)'}
        />
      </div>

      {/* Chart */}
      <div className="card animate-fade-up-2" style={{ padding: 'var(--spacing-lg)' }}>
        {/* Hero: profit bulan berjalan vs bulan lalu */}
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 12, flexWrap: 'wrap', marginBottom: 4 }}>
          <span style={{ fontSize: 12, color: 'var(--text-muted)', fontWeight: 600 }}>Profit Bulan Ini</span>
          <span style={{ fontFamily: "'Manrope', sans-serif", fontSize: 26, fontWeight: 800, color: profit >= 0 ? 'var(--success)' : 'var(--danger)', letterSpacing: '-0.03em' }}>
            {formatRp(profit)}
          </span>
          <TrendChipInline change={pctChange(profit, prev.profit)} />
          <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>vs bulan lalu</span>
        </div>

        {periodStats && (
          <div style={{ display: 'flex', alignItems: 'center', gap: 20, flexWrap: 'wrap', fontSize: 12, color: 'var(--text-muted)' }}>
            <span>High: <span style={{ color: 'var(--info)', fontWeight: 700 }}>{formatRp(periodStats.high)}</span></span>
            <span>Low: <span style={{ color: 'var(--warning)', fontWeight: 700 }}>{formatRp(periodStats.low)}</span></span>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>Change: <TrendChipInline change={periodStats.change} /></span>
          </div>
        )}

        {/* Chart header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', margin: '14px 0' }}>
          <div>
            <h3 style={{ fontFamily: "'Manrope', sans-serif", fontSize: '14px', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '2px' }}>
              Grafik Keuangan
            </h3>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>{periodLabel}</div>
          </div>
          <div style={{ display: 'flex', gap: '4px' }}>
            {(['minggu', 'bulan', 'tahun'] as ChartPeriod[]).map(p => (
              <button key={p}
                className={`btn btn-sm ${chartPeriod === p ? 'btn-primary' : 'btn-secondary'}`}
                onClick={() => setChartPeriod(p)}
                style={{ fontSize: '11px', padding: '4px 12px' }}>
                {p === 'minggu' ? 'Minggu' : p === 'bulan' ? 'Bulan' : 'Tahun'}
              </button>
            ))}
          </div>
        </div>

        {/* Legend */}
        <div style={{ display: 'flex', gap: '20px', marginBottom: '12px' }}>
          {[
            { color: 'var(--success)', label: 'Total Penjualan' },
            { color: 'var(--danger)',  label: 'Pengeluaran' },
            { color: 'var(--accent)',  label: 'Profit' },
          ].map(({ color, label }) => (
            <div key={label} style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <div style={{ width: 24, height: 2.5, background: color, borderRadius: 2 }} />
              <span style={{ fontSize: '11px', color: 'var(--text-secondary)', fontWeight: 500 }}>{label}</span>
            </div>
          ))}
        </div>

        {/* SVG chart */}
        <div style={{ height: 260, width: '100%' }}>
          <LineChart data={chartData} series={keuanganSeries} loading={chartLoading} referenceLabel={todayLabel} />
        </div>
      </div>

      {error && <div className="alert alert-danger">{error}</div>}

      {/* Transaction table */}
      {transaksis.length === 0 ? <EmptyState message="Belum ada transaksi bulan ini" icon="keuangan" /> : (
        <div className="animate-fade-up-2 card" style={{ overflow: 'hidden' }}>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Nama</TableHead>
                <TableHead>Kategori</TableHead>
                <TableHead>Tanggal</TableHead>
                <TableHead align="right">Jumlah</TableHead>
                <TableHead align="right">Aksi</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {transaksis.map(t => (
                <TableRow key={t.id} style={{ borderLeft: `3px solid ${t.jenis === 'pendapatan' ? 'var(--success)' : 'var(--danger)'}` }}>
                  <TableCell data-label="Nama" style={{ fontWeight: 500 }}>
                    {t.nama}
                    {t.isAutoGenerated && (
                      <span style={{ marginLeft: 6, padding: '1px 6px', background: 'var(--accent-light)', color: 'var(--accent)', borderRadius: 'var(--radius-full)', fontSize: '10px', fontWeight: 700 }}>Auto</span>
                    )}
                  </TableCell>
                  <TableCell data-label="Kategori" style={{ color: 'var(--text-muted)' }}>{t.kategori || '—'}</TableCell>
                  <TableCell data-label="Tanggal" style={{ color: 'var(--text-muted)' }}>{formatTgl(t.tanggal)}</TableCell>
                  <TableCell align="right" data-label="Jumlah" style={{ fontWeight: 700, color: t.jenis === 'pendapatan' ? 'var(--success)' : 'var(--danger)', fontFamily: "'Manrope', sans-serif" }}>
                    {t.jenis === 'pendapatan' ? '+' : '−'}{formatRp(t.jumlah)}
                  </TableCell>
                  <TableCell align="right" data-label="Aksi">
                    {!t.isAutoGenerated && (
                      <button className="btn btn-xs" style={{ background: 'var(--danger-light)', color: 'var(--danger)' }} onClick={() => setConfirm(t)}>Hapus</button>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
            <TableFooter>
              <TableRow>
                <TableCell colSpan={3}>Total Bulan Ini</TableCell>
                <TableCell align="right" data-label="Total Bulan Ini" colSpan={2} style={{ color: profit >= 0 ? 'var(--success)' : 'var(--danger)', fontFamily: "'Manrope', sans-serif" }}>
                  {formatRp(profit)}
                </TableCell>
              </TableRow>
            </TableFooter>
          </Table>
        </div>
      )}

      {/* Modal form */}
      {showForm && (
        <Modal width={420}>
          <div className="modal-header">
            <h3>Catat Transaksi Manual</h3>
            <button className="modal-close" onClick={() => { setShowForm(false); setError('') }}>✕</button>
          </div>
          <div className="modal-body">
            {error && <div className="alert alert-danger" style={{ marginBottom: 12 }}>{error}</div>}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', marginBottom: 'var(--spacing-lg)' }}>
              <FormField label="Jenis">
                <select value={form.jenis} onChange={e => setForm(f => ({ ...f, jenis: e.target.value }))}>
                  <option value="pendapatan">Pendapatan</option>
                  <option value="pengeluaran">Pengeluaran</option>
                </select>
              </FormField>
              {([{ label: 'Nama', key: 'nama', required: true }, { label: 'Kategori', key: 'kategori' }] as { label: string; key: string; required?: boolean }[]).map(({ label, key, required }) => (
                <FormField key={key} label={label} required={required}>
                  <input value={(form as any)[key]} onChange={e => setForm(f => ({ ...f, [key]: e.target.value }))} />
                </FormField>
              ))}
              <FormField label="Jumlah (Rp)" required>
                <input type="number" value={form.jumlah} onChange={e => setForm(f => ({ ...f, jumlah: e.target.value }))} />
              </FormField>
              <FormField label="Tanggal" required>
                <input type="date" value={form.tanggal} onChange={e => setForm(f => ({ ...f, tanggal: e.target.value }))} />
              </FormField>
            </div>
            <div className="modal-footer">
              <button className="btn btn-secondary btn-sm" onClick={() => { setShowForm(false); setError('') }}>Batal</button>
              <button className="btn btn-primary btn-sm" onClick={handleSubmit}>Simpan</button>
            </div>
          </div>
        </Modal>
      )}

      {confirm && (
        <ConfirmDialog
          title="Hapus Transaksi"
          message={`Hapus transaksi "${confirm.nama}"?`}
          onConfirm={async () => { await dispatch(deleteTransaksi(confirm.id)); setConfirm(null) }}
          onCancel={() => setConfirm(null)}
          confirmLabel="Hapus"
          danger
        />
      )}
    </div>
  )
}
