import { getDb } from '../db'
import { generateId, nowIso, bulanLalu } from '../utils'
import { Transaksi } from '../types'

function rowToTransaksi(row: any): Transaksi {
  return { id: row.id, jenis: row.jenis, nama: row.nama, kategori: row.kategori, jumlah: row.jumlah, hppSnapshot: row.hpp_snapshot ?? undefined, tanggal: row.tanggal, pesananId: row.pesanan_id, sourceType: row.source_type, sourceId: row.source_id, isAutoGenerated: Boolean(row.is_auto_generated), createdAt: row.created_at }
}

export const transaksiRepository = {
  findAll(): Transaksi[] { return getDb().prepare('SELECT * FROM transaksi ORDER BY tanggal DESC, created_at DESC').all().map(rowToTransaksi) },
  findById(id: string): Transaksi | null { const row = getDb().prepare('SELECT * FROM transaksi WHERE id = ?').get(id); return row ? rowToTransaksi(row) : null },
  findByBulan(bulan: string): Transaksi[] { return getDb().prepare('SELECT * FROM transaksi WHERE tanggal LIKE ? ORDER BY tanggal DESC').all(`${bulan}%`).map(rowToTransaksi) },
  createManual(payload: any): Transaksi | null {
    const id = generateId(); const now = nowIso()
    getDb().prepare("INSERT INTO transaksi (id, jenis, nama, kategori, jumlah, tanggal, pesanan_id, source_type, source_id, is_auto_generated, created_at) VALUES (?, ?, ?, ?, ?, ?, NULL, 'manual', NULL, 0, ?)")
      .run(id, payload.jenis, payload.nama, payload.kategori ?? null, payload.jumlah, payload.tanggal, now)
    return this.findById(id)
  },
  createAutoFromPesanan(pesananId: string, nama: string, jumlah: number, hpp: number, tanggal: string): Transaksi | null {
    const id = generateId(); const now = nowIso()
    getDb().prepare("INSERT INTO transaksi (id, jenis, nama, kategori, jumlah, hpp_snapshot, tanggal, pesanan_id, source_type, source_id, is_auto_generated, created_at) VALUES (?, 'pendapatan', ?, 'Pesanan', ?, ?, ?, ?, 'pesanan', ?, 1, ?)")
      .run(id, nama, jumlah, hpp, tanggal, pesananId, pesananId, now)
    return this.findById(id)
  },
  createAutoFromRestock(materialId: string, nama: string, jumlah: number, tanggal: string): Transaksi | null {
    const id = generateId(); const now = nowIso()
    getDb().prepare("INSERT INTO transaksi (id, jenis, nama, kategori, jumlah, tanggal, pesanan_id, source_type, source_id, is_auto_generated, created_at) VALUES (?, 'pengeluaran', ?, 'Pembelian Material', ?, ?, NULL, 'manual', ?, 1, ?)")
      .run(id, nama, jumlah, tanggal, materialId, now)
    return this.findById(id)
  },
  delete(id: string): boolean {
    const existing = this.findById(id)
    if (!existing || existing.isAutoGenerated) return false
    return (getDb().prepare('DELETE FROM transaksi WHERE id = ? AND is_auto_generated = 0').run(id) as any).changes > 0
  },
  sumPendapatanBulanIni(): number {
    const month = new Date().toISOString().slice(0, 7)
    return (getDb().prepare("SELECT COALESCE(SUM(CASE WHEN is_auto_generated = 1 THEN jumlah - COALESCE(hpp_snapshot, 0) ELSE jumlah END), 0) as total FROM transaksi WHERE jenis = 'pendapatan' AND tanggal LIKE ?").get(`${month}%`) as any).total
  },
  sumPengeluaranBulanIni(): number {
    const month = new Date().toISOString().slice(0, 7)
    return (getDb().prepare("SELECT COALESCE(SUM(jumlah), 0) as total FROM transaksi WHERE jenis = 'pengeluaran' AND tanggal LIKE ?").get(`${month}%`) as any).total
  },
  sumPendapatanBulanLalu(): number {
    const month = bulanLalu()
    return (getDb().prepare("SELECT COALESCE(SUM(CASE WHEN is_auto_generated = 1 THEN jumlah - COALESCE(hpp_snapshot, 0) ELSE jumlah END), 0) as total FROM transaksi WHERE jenis = 'pendapatan' AND tanggal LIKE ?").get(`${month}%`) as any).total
  },
  sumPengeluaranBulanLalu(): number {
    const month = bulanLalu()
    return (getDb().prepare("SELECT COALESCE(SUM(jumlah), 0) as total FROM transaksi WHERE jenis = 'pengeluaran' AND tanggal LIKE ?").get(`${month}%`) as any).total
  },
  rataRataNilaiJual(): number {
    return (getDb().prepare("SELECT COALESCE(AVG(jumlah), 0) as avg FROM transaksi WHERE jenis = 'pendapatan' AND is_auto_generated = 1").get() as any).avg
  }
}
